# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player_1_Yana.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1364, 762)
        MainWindow.setStyleSheet("background-color: #d0e6fd;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.gridLayout = QtWidgets.QGridLayout(self.login_page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 166, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.login_page)
        self.frame_4.setMaximumSize(QtCore.QSize(701, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"border-radius: 15px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(124, 124, 124);\n"
"border-radius:10px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lineEdit.setStyleSheet("background-color: rgb(124, 124, 124);\n"
"border-radius: 15px;\n"
"border: 0;\n"
"padding: 0 10px;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"font: 11pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(124, 124, 124);\n"
"color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    border: 1px solid #000;\n"
"    color: #000\n"
"}")
        self.pushButton_6.setAutoRepeatDelay(300)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 266, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.login_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.PrevLesson = QtWidgets.QPushButton(self.page_2)
        self.PrevLesson.setGeometry(QtCore.QRect(1020, 20, 111, 41))
        self.PrevLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PrevLesson.setStyleSheet("border-radius: 17px;\n"
"background-color:#97aafe;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"font-weight: 700;")
        self.PrevLesson.setObjectName("PrevLesson")
        self.NextLesson = QtWidgets.QPushButton(self.page_2)
        self.NextLesson.setGeometry(QtCore.QRect(1160, 20, 111, 41))
        self.NextLesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextLesson.setStyleSheet("border-radius: 17px;\n"
"background-color:#97aafe;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"font-weight: 700;")
        self.NextLesson.setObjectName("NextLesson")
        self.Categories = QtWidgets.QTreeWidget(self.page_2)
        self.Categories.setGeometry(QtCore.QRect(0, 100, 211, 445))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Categories.sizePolicy().hasHeightForWidth())
        self.Categories.setSizePolicy(sizePolicy)
        self.Categories.setMaximumSize(QtCore.QSize(16777215, 445))
        self.Categories.setStyleSheet("background-color: transparent;\n"
"border: 0;\n"
"font-weight: 600;\n"
"font-size: 14px;")
        self.Categories.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.Categories.setUniformRowHeights(False)
        self.Categories.setHeaderHidden(True)
        self.Categories.setObjectName("Categories")
        font = QtGui.QFont()
        font.setKerning(True)
        self.Categories.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.Categories)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon_lock_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.Categories)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.Categories)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.Categories)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.Categories)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        self.Categories.header().setDefaultSectionSize(100)
        self.Categories.header().setSortIndicatorShown(False)
        self.stackedwidget = QtWidgets.QStackedWidget(self.page_2)
        self.stackedwidget.setGeometry(QtCore.QRect(210, 80, 1061, 561))
        self.stackedwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedwidget.setStyleSheet("background-color: transparent;")
        self.stackedwidget.setObjectName("stackedwidget")
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.video_page)
        self.graphicsView_2.setGeometry(QtCore.QRect(290, 450, 191, 111))
        self.graphicsView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphicsView_2.setStyleSheet("background-color: #e3f0fe;")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.For_video = QtWidgets.QGraphicsView(self.video_page)
        self.For_video.setGeometry(QtCore.QRect(10, 0, 1051, 431))
        self.For_video.setStyleSheet("background-color: #e3f0fe;")
        self.For_video.setObjectName("For_video")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.video_page)
        self.graphicsView_4.setGeometry(QtCore.QRect(869, 450, 191, 111))
        self.graphicsView_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphicsView_4.setStyleSheet("background-color: #e3f0fe;")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.video_page)
        self.graphicsView.setGeometry(QtCore.QRect(10, 450, 191, 111))
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphicsView.setStyleSheet("background-color: #e3f0fe;")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_5 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_5.setGeometry(QtCore.QRect(924, 480, 75, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("background-color:transparent;")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.video_page)
        self.pushButton.setGeometry(QtCore.QRect(510, 170, 75, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: transparent;")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 480, 75, 51))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color:transparent;")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon_unlock_(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 480, 75, 51))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color:transparent;")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.video_page)
        self.graphicsView_3.setGeometry(QtCore.QRect(579, 450, 191, 111))
        self.graphicsView_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphicsView_3.setStyleSheet("background-color: #e3f0fe;")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_3.setGeometry(QtCore.QRect(349, 480, 75, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color:transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalSlider = QtWidgets.QSlider(self.video_page)
        self.horizontalSlider.setGeometry(QtCore.QRect(390, 382, 321, 22))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #d0e6fd, stop:1 #d0e6fd);\n"
"    border: 1px solid #000000;\n"
"    height: 3px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #d0e6fd;\n"
"    border: 1px solid #000000;\n"
"    width: 15px;\n"
"    margin: -7px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_7 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_7.setGeometry(QtCore.QRect(500, 404, 30, 23))
        self.pushButton_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("previous(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 404, 30, 23))
        self.pushButton_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("stop-button(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.video_page)
        self.pushButton_9.setGeometry(QtCore.QRect(560, 404, 30, 23))
        self.pushButton_9.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("next-button(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3 = QtWidgets.QLabel(self.video_page)
        self.label_3.setGeometry(QtCore.QRect(370, 369, 361, 61))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius: 30px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.graphicsView_3.raise_()
        self.graphicsView_2.raise_()
        self.For_video.raise_()
        self.graphicsView_4.raise_()
        self.graphicsView.raise_()
        self.pushButton_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.label_3.raise_()
        self.pushButton_9.raise_()
        self.pushButton_8.raise_()
        self.horizontalSlider.raise_()
        self.pushButton_7.raise_()
        self.stackedwidget.addWidget(self.video_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.about_label = QtWidgets.QLabel(self.about_page)
        self.about_label.setGeometry(QtCore.QRect(20, 130, 1031, 371))
        self.about_label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(124, 124, 124);\n"
"border-radius:10px")
        self.about_label.setAlignment(QtCore.Qt.AlignCenter)
        self.about_label.setObjectName("about_label")
        self.start_modul = QtWidgets.QPushButton(self.about_page)
        self.start_modul.setGeometry(QtCore.QRect(410, 510, 251, 31))
        self.start_modul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_modul.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(124, 124, 124);\n"
"border-radius:10px")
        self.start_modul.setObjectName("start_modul")
        self.name_label = QtWidgets.QLabel(self.about_page)
        self.name_label.setGeometry(QtCore.QRect(20, 10, 1031, 111))
        self.name_label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(124, 124, 124);\n"
"border-radius:10px")
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.label_4 = QtWidgets.QLabel(self.about_page)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 1061, 571))
        self.label_4.setStyleSheet("background-color: #e3f0fe;")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.about_label.raise_()
        self.start_modul.raise_()
        self.name_label.raise_()
        self.stackedwidget.addWidget(self.about_page)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Logindan Video_page ga o'tish
        self.pushButton_6.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))

        #Modul ustiga bosilganda u haqida ga olib o'tish "About" ga
        self.Categories.itemClicked.connect(self.handle_category_item_click)

        # Start module bosilganda yana video page ga olib o'tish
        self.start_modul.clicked.connect(lambda: self.stackedwidget.setCurrentWidget(self.video_page))



    def handle_category_item_click(self, item, column):
        if item.parent() is None:
                # This is a top-level item
                self.stackedwidget.setCurrentWidget(self.about_page)
                category_name = item.text(0)  # Top-level category name
                self.name_label.setText(f"Name: {category_name}")
                self.name_label.setWordWrap(True)
        else:
             print("Xato")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Player"))
        self.label.setText(_translate("MainWindow", "Kalit so\'z"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Kalit so\'zni kiriting"))
        self.pushButton_6.setText(_translate("MainWindow", "Login"))
        self.PrevLesson.setText(_translate("MainWindow", "Oldingi dars"))
        self.NextLesson.setText(_translate("MainWindow", "Keyingi dars"))
        self.Categories.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Categories.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.Categories.isSortingEnabled()
        self.Categories.setSortingEnabled(False)
        self.Categories.topLevelItem(0).setText(0, _translate("MainWindow", "1-modul"))
        self.Categories.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1-dars"))
        self.Categories.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2-dars"))
        self.Categories.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "3-dars"))
        self.Categories.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "4-dars"))
        self.Categories.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "5-dars"))
        self.Categories.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "6-dars"))
        self.Categories.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "7-dars"))
        self.Categories.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "8-dars"))
        self.Categories.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "9-dars"))
        self.Categories.topLevelItem(1).setText(0, _translate("MainWindow", "2-modul"))
        self.Categories.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "2-dars"))
        self.Categories.topLevelItem(2).setText(0, _translate("MainWindow", "3-modul"))
        self.Categories.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "1-dars"))
        self.Categories.topLevelItem(3).setText(0, _translate("MainWindow", "4-modul"))
        self.Categories.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "1-dars"))
        self.Categories.topLevelItem(4).setText(0, _translate("MainWindow", "5-modul"))
        self.Categories.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "1-dars"))
        self.Categories.setSortingEnabled(__sortingEnabled)
        self.about_label.setText(_translate("MainWindow", "About Page"))
        self.start_modul.setText(_translate("MainWindow", "Start Module"))
        self.name_label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.name_label.setText(_translate("MainWindow", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
